/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.call.center;

import com.call.center.employees.Manager;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }

  @Test
  void mockEmployee() {
    Employee employee = new MockEmployee();
    new Manager(employee);
  }
}

class MockEmployee extends Employee {
  @Override
  public String getName() {
    return "Nick";
  }
}
